package com.ehaoyao.logistics.jd.model.ordercenter;
// Generated 2016-4-13 22:30:12 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ExpressDetail generated by hbm2java
 */
@Entity
@Table(name = "express_detail", catalog = "ordercenter")
public class ExpressDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3270212481021921377L;
	private Long id;
	private String expressCom;
	private String expressContent;
	private String expressId;
	private String expressState;
	private byte isSent;

	public ExpressDetail() {
	}

	public ExpressDetail(byte isSent) {
		this.isSent = isSent;
	}

	public ExpressDetail(String expressCom, String expressContent, String expressId, String expressState, byte isSent) {
		this.expressCom = expressCom;
		this.expressContent = expressContent;
		this.expressId = expressId;
		this.expressState = expressState;
		this.isSent = isSent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "express_com")
	public String getExpressCom() {
		return this.expressCom;
	}

	public void setExpressCom(String expressCom) {
		this.expressCom = expressCom;
	}

	@Column(name = "express_content", length = 5000)
	public String getExpressContent() {
		return this.expressContent;
	}

	public void setExpressContent(String expressContent) {
		this.expressContent = expressContent;
	}

	@Column(name = "express_id")
	public String getExpressId() {
		return this.expressId;
	}

	public void setExpressId(String expressId) {
		this.expressId = expressId;
	}

	@Column(name = "express_state")
	public String getExpressState() {
		return this.expressState;
	}

	public void setExpressState(String expressState) {
		this.expressState = expressState;
	}

	@Column(name = "is_sent", nullable = false)
	public byte getIsSent() {
		return this.isSent;
	}

	public void setIsSent(byte isSent) {
		this.isSent = isSent;
	}

}
